<template>
  <v-container>
    <h1 class="text-center">Welcome to GhostPipe!</h1>
    <Suggested></Suggested>
    <p class="text-center">Suggested Feed is autogenerated and is not personalized. </p>
  </v-container>
</template>

<script>
import Suggested from "./Suggested.vue";

export default {
    name: "Template",
    data: () => {
    },
    components: { Suggested }
}
</script>
